title: Homelab
startUrl: "{{HOMEPAGE_VAR_HOMEPAGE_URL}}"
theme: dark
color: emerald
target: _self

layout:
  Core:
    style: row
    columns: 4
  Apps:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 4
