http:
  middlewares:
    lan-only:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"

    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: false
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: same-origin

    internal-error-pages:
      errors:
        status:
          - "400-599"
        service: error-pages@docker
        query: /index.html

    internal-app:
      chain:
        middlewares:
          - lan-only
          - internal-error-pages
          - security-headers
