services:
  docs:
    container_name: docs
    image: node:22-alpine
    restart: unless-stopped
    working_dir: /docs
    command: sh -c "rm -rf node_modules .docusaurus && npm ci && npm run start -- --host 0.0.0.0 --port 3000"
    environment:
      TZ: ${TZ}
    volumes:
      - ../../docs:/docs
    networks:
      - internal_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.docs.rule=Host(`${DOCS_HOST}`)
      - traefik.http.routers.docs.entrypoints=websecure
      - traefik.http.routers.docs.tls=true
      - traefik.http.routers.docs.tls.certresolver=internalresolver
      - traefik.http.routers.docs.middlewares=internal-app@file
      - traefik.http.services.docs.loadbalancer.server.port=3000
      - traefik.docker.network=internal_network
